'use client';

import { useState, useRef } from 'react';
import { Info } from 'lucide-react';

const COLORS = {
  spend:     '#8BE34D',
  awareness: '#8B5CF6',
  traffic:   '#F59E0B',
  leads:     '#3B82F6',
};
const TITLES = {
  spend:     'Daily Spend',
  awareness: 'Daily Awareness',
  traffic:   'Daily Traffic',
  leads:     'Daily Leads',
};
const METRICS = [
  { key: 'spend',     label: 'Spend' },
  { key: 'awareness', label: 'Awareness' },
  { key: 'traffic',   label: 'Traffic' },
  { key: 'leads',     label: 'Leads' },
];
/* Penjelasan tooltip icon (i) — profesional, ikut metrik aktif */
const INFO_TEXT = {
  spend:     'Daily advertising spend charged by Meta across all campaigns, plotted for each day in the selected period.',
  awareness: 'Daily ad impressions — the number of times your ads were displayed across all campaigns each day.',
  traffic:   'Daily link clicks generated by your traffic campaigns — a measure of how effectively ads drive visits.',
  leads:     'Daily leads captured by your conversion campaigns — potential customers who submitted their details.',
};

function fmtVal(m, v) {
  if (m === 'spend') {
    if (v >= 1000000) return 'Rp ' + (v / 1000000).toFixed(1).replace('.0', '') + 'M';
    if (v >= 1000)    return 'Rp ' + (v / 1000).toFixed(0) + 'K';
    return 'Rp ' + Math.round(v);
  }
  return Math.round(v).toLocaleString('id-ID');
}
function fmtAxis(m, v) {
  if (v >= 1000000) return (v / 1000000).toFixed(0) + 'M';
  if (v >= 1000)    return (v / 1000).toFixed(0) + 'K';
  return Math.round(v);
}

// Catmull-Rom → cubic bezier untuk kurva mulus
function smoothPath(pts) {
  if (pts.length < 2) return '';
  let d = `M ${pts[0].x.toFixed(2)} ${pts[0].y.toFixed(2)}`;
  for (let i = 0; i < pts.length - 1; i++) {
    const p0 = pts[i - 1] || pts[i];
    const p1 = pts[i];
    const p2 = pts[i + 1];
    const p3 = pts[i + 2] || p2;
    const c1x = p1.x + (p2.x - p0.x) / 6;
    const c1y = p1.y + (p2.y - p0.y) / 6;
    const c2x = p2.x - (p3.x - p1.x) / 6;
    const c2y = p2.y - (p3.y - p1.y) / 6;
    d += ` C ${c1x.toFixed(2)} ${c1y.toFixed(2)}, ${c2x.toFixed(2)} ${c2y.toFixed(2)}, ${p2.x.toFixed(2)} ${p2.y.toFixed(2)}`;
  }
  return d;
}

export default function AreaChart({ data, dates, today }) {
  const [metric, setMetric] = useState('spend');
  const [hover, setHover]   = useState(null); // { idx, xPct, yPct }
  const [showInfo, setShowInfo] = useState(false); // tooltip icon (i)
  const wrapRef = useRef(null);

  const arr   = data[metric] || [];
  const n     = arr.length;
  const col   = COLORS[metric];
  const dayOf = (i) => (dates && dates[i] != null ? dates[i] : i + 1);

  // Hanya slot yang punya data jadi titik garis; posisi-x tetap ikut indeks
  // penuh, jadi hari yang belum ada datanya tampil sebagai ruang kosong.
  const valid = [];
  arr.forEach((v, i) => { if (v != null) valid.push({ v, i, x: n > 1 ? (i / (n - 1)) * 100 : 50 }); });
  const max = Math.max.apply(null, valid.length ? valid.map(p => p.v) : [1]) || 1;
  const pts = valid.map(p => ({ ...p, y: 92 - (p.v / max) * 84 }));

  const line = smoothPath(pts);
  let area = '';
  if (pts.length >= 2) {
    area = `${line} L ${pts[pts.length - 1].x.toFixed(2)} 100 L ${pts[0].x.toFixed(2)} 100 Z`;
  }

  const yLabels = [];
  for (let s = 4; s >= 0; s--) yLabels.push(fmtAxis(metric, (max * s) / 4));

  // Sumbu-x: tampilkan semua tanggal kalau ≤31 hari, selebihnya di-sampling
  const xTicks = [];
  if (n > 0) {
    if (n <= 31) {
      for (let i = 0; i < n; i++) xTicks.push(i);
    } else {
      const step = Math.max(1, Math.round(n / 12));
      for (let i = 0; i < n; i += step) xTicks.push(i);
      if (xTicks[xTicks.length - 1] !== n - 1) xTicks.push(n - 1);
    }
  }

  function onMove(e) {
    if (!wrapRef.current || pts.length === 0) return;
    const r = wrapRef.current.getBoundingClientRect();
    const ratio = Math.min(1, Math.max(0, (e.clientX - r.left) / r.width)) * 100;
    let best = pts[0];
    for (const p of pts) if (Math.abs(p.x - ratio) < Math.abs(best.x - ratio)) best = p;
    setHover({ idx: best.i, xPct: best.x, yPct: best.y, clientX: e.clientX, clientY: e.clientY });
  }

  return (
    <div style={{
      background: 'var(--cd)',
      border: '1px solid var(--br)',
      borderRadius: '18px',
      boxShadow: 'var(--shadow)',
      padding: '18px 20px',
      display: 'flex',
      flexDirection: 'column',
      minHeight: 0,
      height: '100%',
    }}>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px', flexShrink: 0, flexWrap: 'wrap', rowGap: '8px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '7px' }}>
          <span key={metric} style={{
            fontSize: '15px', fontWeight: 600, color: 'var(--t1)',
            animation: 'wdSoftIn 0.35s cubic-bezier(0.4,0,0.2,1)',
          }}>{TITLES[metric]}</span>
          <span
            onMouseEnter={() => setShowInfo(true)}
            onMouseLeave={() => setShowInfo(false)}
            style={{ position: 'relative', display: 'inline-flex', cursor: 'help' }}
          >
            <Info size={13} color="var(--t3)" />
            {showInfo && (
              <div style={{
                position: 'absolute', top: '22px', left: '-10px', zIndex: 60,
                width: '260px', padding: '9px 12px',
                background: 'var(--tooltip-bg)', border: '1px solid var(--tooltip-br)',
                color: 'var(--tooltip-tx)', borderRadius: '9px',
                fontSize: '11.5px', fontWeight: 400, lineHeight: 1.6,
                boxShadow: 'var(--pop-shadow)', pointerEvents: 'none',
                animation: 'wdScaleIn 0.12s cubic-bezier(0.4,0,0.2,1)',
              }}>
                {INFO_TEXT[metric]}
              </div>
            )}
          </span>
        </div>
        <div style={{ display: 'flex', gap: '3px', background: 'var(--hover)', padding: '3px', borderRadius: '9px' }}>
          {METRICS.map((m) => {
            const active = metric === m.key;
            return (
              <button key={m.key} onClick={() => setMetric(m.key)} style={{
                padding: '5px 12px', border: 'none', borderRadius: '7px', fontSize: '12px', fontWeight: 500,
                background: active ? COLORS[m.key] : 'transparent',
                color: active ? '#0A0F06' : 'var(--t2)',
                cursor: 'pointer', transition: 'all 0.18s',
              }}>{m.label}</button>
            );
          })}
        </div>
      </div>

      {/* Chart body */}
      <div style={{ display: 'flex', gap: '10px', flex: 1, minHeight: 0 }}>
        {/* Y axis */}
        <div style={{
          display: 'flex', flexDirection: 'column', justifyContent: 'space-between',
          fontSize: '10px', color: 'var(--t3)', textAlign: 'right', minWidth: '36px', paddingBottom: '20px',
        }}>
          {yLabels.map((l, i) => <div key={i}>{l}</div>)}
        </div>

        {/* Plot */}
        <div style={{ flex: 1, display: 'flex', flexDirection: 'column', minHeight: 0 }}>
          <div
            ref={wrapRef}
            onMouseMove={onMove}
            onMouseLeave={() => setHover(null)}
            style={{ flex: 1, position: 'relative', minHeight: 0, cursor: 'crosshair' }}
          >
            {/* Grid */}
            <div style={{ position: 'absolute', inset: 0 }}>
              {[0, 1, 2, 3, 4].map((i) => (
                <div key={i} style={{
                  position: 'absolute', top: (i / 4) * 100 + '%', left: 0, right: 0,
                  borderTop: '1px solid var(--grid)',
                }} />
              ))}
            </div>

            {/* Area + line */}
            <svg viewBox="0 0 100 100" preserveAspectRatio="none" style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', overflow: 'visible' }}>
              <defs>
                <linearGradient id={`fill-${metric}`} x1="0" y1="0" x2="0" y2="1">
                  <stop offset="0%"   stopColor={col} stopOpacity="0.28" />
                  <stop offset="100%" stopColor={col} stopOpacity="0" />
                </linearGradient>
              </defs>
              {area && (
                <path key={`a-${metric}`} d={area} fill={`url(#fill-${metric})`} stroke="none"
                  style={{
                    transformOrigin: 'bottom',
                    animation: 'wdAreaGrow 0.6s cubic-bezier(0.4,0,0.2,1)',
                  }} />
              )}
              {line && (
                <path key={`l-${metric}`} d={line} fill="none" stroke={col} strokeWidth="2"
                  pathLength="1" strokeDasharray="1"
                  vectorEffect="non-scaling-stroke" strokeLinejoin="round" strokeLinecap="round"
                  style={{
                    filter: `drop-shadow(0 2px 5px ${col}55)`,
                    animation: 'wdDrawLine 0.7s cubic-bezier(0.4,0,0.2,1)',
                  }} />
              )}
            </svg>

            {/* Titik data (tampil saat hari aktif masih sedikit) */}
            {pts.length <= 7 && pts.map((p) => (
              <div key={p.i} style={{
                position: 'absolute', left: p.x + '%', top: p.y + '%',
                width: '8px', height: '8px', borderRadius: '50%', background: col,
                border: '2px solid var(--cd)', transform: 'translate(-50%,-50%)', pointerEvents: 'none',
              }} />
            ))}

            {/* Hover guide */}
            {hover && (
              <>
                <div style={{
                  position: 'absolute', top: 0, bottom: 0, left: hover.xPct + '%',
                  width: '1px', background: 'var(--br-strong)', pointerEvents: 'none',
                }} />
                <div style={{
                  position: 'absolute', left: hover.xPct + '%', top: hover.yPct + '%',
                  width: '9px', height: '9px', borderRadius: '50%', background: col,
                  border: '2px solid var(--cd)', transform: 'translate(-50%,-50%)',
                  boxShadow: `0 0 8px ${col}`, pointerEvents: 'none',
                }} />
              </>
            )}
          </div>

          {/* X axis */}
          <div style={{ position: 'relative', height: '14px', marginTop: '6px' }}>
            {xTicks.map((i) => {
              const isToday = i === today;
              return (
                <span key={i} style={{
                  position: 'absolute', left: (n > 1 ? (i / (n - 1)) * 100 : 50) + '%',
                  transform: 'translateX(-50%)', fontSize: n > 20 ? '8px' : '9px',
                  color: isToday ? COLORS.spend : 'var(--t3)', fontWeight: isToday ? 700 : 400,
                }}>{dayOf(i)}</span>
              );
            })}
          </div>
        </div>
      </div>

      {/* Tooltip */}
      {hover && arr[hover.idx] !== undefined && (
        <div style={{
          position: 'fixed', left: hover.clientX + 14, top: hover.clientY - 44,
          background: 'var(--tooltip-bg)', border: '1px solid var(--tooltip-br)', borderRadius: '8px',
          padding: '7px 11px', pointerEvents: 'none', zIndex: 100, whiteSpace: 'nowrap',
          boxShadow: 'var(--pop-shadow)',
        }}>
          <div style={{ fontSize: '10px', color: 'rgba(255,255,255,0.65)', marginBottom: '3px' }}>
            Day {dayOf(hover.idx)}{hover.idx === today ? ' · today' : ''}
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
            <span style={{ width: '7px', height: '7px', borderRadius: '50%', background: col }} />
            <span style={{ fontSize: '13px', fontWeight: 600, color: 'var(--tooltip-tx)' }}>{fmtVal(metric, arr[hover.idx])}</span>
          </div>
        </div>
      )}
    </div>
  );
}
